version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: next-auth-db
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-auth-db
    volumes:
      - next-auth-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  next-auth-data:
    name: next-auth-data

